@baseUrl = http://localhost:3000/api/orders
@page = 1
@pageLimit = 10

### GET orders
GET {{baseUrl}}?page={{page}}&limit={{pageLimit}}

### GET cancelled orders
GET {{baseUrl}}?status=CANCELLED

### GET cancelled orders by status
GET {{baseUrl}}/DELIVERED

### Create order
POST {{baseUrl}}
Content-Type: application/json

{
  "totalItems": 5,
  "totalAmount": 100
}

### Get order by id
@id = 011f4402-08ab-45f5-baac-179b937ec491
GET {{baseUrl}}/id/{{id}}
