@baseUrl = http://localhost:3000/api/orders
@page = 1
@pageLimit = 10

### GET orders
GET {{baseUrl}}?page={{page}}&limit={{pageLimit}}

### Create order
POST {{baseUrl}}
Content-Type: application/json

{
  "totalItems": 5,
  "totalAmount": 100
}

### Get order by id
GET {{baseUrl}}/49
